#!/usr/bin/env python3
"""Sync the three run-difficulty authoring workbooks to isolated runtime CSV packages."""

from __future__ import annotations

import argparse
import shutil
import sys
import tempfile
from pathlib import Path

from openpyxl import load_workbook

try:
    from . import sync_xlsx_to_csv as base_sync
except ImportError:
    import sync_xlsx_to_csv as base_sync


ROOT = Path(__file__).resolve().parents[2]
DATA_DIR = ROOT / "Content" / "Data"
DIFFICULTY_DIR = DATA_DIR / "Difficulty"
DIFFICULTIES = ("Party", "Standard", "Nightmare")
DIFFICULTY_TABLES = (
    "tblEnemies",
    "tblEnemyAbilities",
    "tblBossPhases",
    "tblEnemyCombatStats",
    "tblEnemyShardDrops",
    "tblStages",
    "tblEncounters",
    "tblEncounterWaves",
    "tblSpawnProfiles",
    "tblSpawnPolicy",
)


def workbook_path(difficulty: str) -> Path:
    return ROOT / "Design" / "Data" / f"ReEchoDifficulty{difficulty}.xlsx"


def generate_workbook(workbook_file: Path, output_dir: Path) -> dict[str, bytes]:
    workbook = load_workbook(workbook_file, data_only=False, read_only=False)
    owners = base_sync.read_export_map(workbook)
    tables = base_sync.workbook_tables(workbook)
    expected_tables = set(DIFFICULTY_TABLES)
    actual_tables = {owner.table for owner in owners}
    if actual_tables != expected_tables:
        raise base_sync.SyncError(
            f"{workbook_file.name}: difficulty table set mismatch "
            f"missing={sorted(expected_tables - actual_tables)} extra={sorted(actual_tables - expected_tables)}"
        )
    # Consolidated difficulty workbooks are generated by artifact-tool and use its native list-validation
    # representation. Row/schema/reference validation below remains authoritative for publish correctness.
    schema_columns = base_sync.load_schema()
    schema_specs = base_sync.load_schema_specs()
    generated: dict[str, bytes] = {}
    output_dir.mkdir(parents=True, exist_ok=True)
    for owner in owners:
        sheet, table = tables[owner.table]
        table_id = base_sync.table_id_for_csv(owner.output_csv)
        rows, _ = base_sync.extract_table(sheet, table, owner.table, table_id, schema_specs[table_id])
        if rows[0] != schema_columns[table_id]:
            raise base_sync.LocatedError(owner.sheet, owner.table, 1, "Header", "Columns do not match schema order")
        generated[owner.output_csv] = base_sync.write_csv(output_dir / owner.output_csv, rows)

    return generated


def validate_as_full_package(difficulty_dir: Path) -> None:
    sys.path.insert(0, str(ROOT / "scripts"))
    import validate_project

    with tempfile.TemporaryDirectory(prefix="reecho_difficulty_validate_", dir=DATA_DIR.parent) as temp:
        assembled = Path(temp)
        for source in DATA_DIR.glob("*.csv"):
            shutil.copy2(source, assembled / source.name)
        for source in difficulty_dir.glob("*.csv"):
            shutil.copy2(source, assembled / source.name)
        validate_project.validate_csv_package(assembled)


def sync_one(difficulty: str, check: bool) -> None:
    source = workbook_path(difficulty)
    if not source.exists():
        raise base_sync.SyncError(f"Difficulty workbook does not exist: {source}")
    with tempfile.TemporaryDirectory(prefix=f"reecho_{difficulty.lower()}_", dir=DATA_DIR.parent) as temp:
        generated_dir = Path(temp)
        generated = generate_workbook(source, generated_dir)
        validate_as_full_package(generated_dir)
        target_dir = DIFFICULTY_DIR / difficulty
        drift = [name for name, data in generated.items() if not (target_dir / name).exists() or (target_dir / name).read_bytes() != data]
        if check:
            if drift:
                raise base_sync.SyncError(f"{difficulty} difficulty CSV drift: {', '.join(sorted(drift))}")
            return
        target_dir.mkdir(parents=True, exist_ok=True)
        for name, data in generated.items():
            (target_dir / name).write_bytes(data)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Validate and compare without writing CSV files.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    base_sync.check_dependencies()
    for difficulty in DIFFICULTIES:
        sync_one(difficulty, args.check)
    print(f"[PASS] Difficulty XLSX packages {'match' if args.check else 'published to'} Content/Data/Difficulty.")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except base_sync.SyncError as exc:
        print(f"[FAIL] {exc}", file=sys.stderr)
        raise SystemExit(1)
